### ISSUE TITLE
新版本设置-样式-平板布局被删除

### ISSUE THREAD

**Issue by 123sdvc354** [3003h/Eros-FE#310]
### 功能描述 / Feature description

希望可以加上

### 自查步骤 / Self-review steps

- [ ] 如果您有足够的时间和能力，并愿意为此功能请求提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/3003h/FEhViewer/issues)，没有找到类似的请求 / I have searched on [Issue Tracker](https://github.com/3003h/FEhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只发起一个功能请求。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request

**Comment by 3003h** [comment]
估计是重构界面给漏了。失误

**Comment by 123sdvc354** [comment]
1.4.13+532    1.4.11+521

**Comment by 123sdvc354** [comment]
1.4.11+521
