### ISSUE TITLE
关闭app后历史纪录会被清空

### ISSUE THREAD

**Issue by r20019xx** [3003h/Eros-FE#339]
### 复现步骤 / Steps to reproduce

1.关闭app
2.再次开启
3.历史纪录被清空

### 预期行为 / Expected behaviour

关闭app后历史纪录不会被清空

### 实际行为 / Actual behaviour

自1.5版本后关闭app后历史纪录会被清空（使用armv8版本） 1.4版本前本地端会储存历史纪录

### FEhViewer 版本号 / FEhViewer version code

1.5.4（534）

### FEhViewer CI 版本 / FEhViewer CI version

https://github.com/3003h/FEhViewer/actions/runs/7055170774

### 平台 / Platform

android

### 系统版本 / System version

HyperOS 1.0

### 设备型号 / Device model

mi 13

### SoC 型号 / SoC model

s8g2

### 应用日志 / App logs

n

### 自查步骤 / Self-review steps

- [ ] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/3003h/FEhViewer/issues)，没有找到类似的问题 / I have searched on [Issue Tracker](https://github.com/3003h/FEhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/3003h/FEhViewer/actions/workflows/release.yml) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/3003h/FEhViewer/actions/workflows/release.yml)

**Comment by 3003h** [comment]
因为有次更新修改了一个属性类型，导致读取旧的历史的时候转换错误就都没法加载出来。类型转换的兼容还没改
要解决的话主动清空一次历史记录，然后远程的也都清理掉，后面就应该都正常了

**Comment by dyphire** [comment]
> 因为有次更新修改了一个属性类型，导致读取旧的历史的时候转换错误就都没法加载出来。类型转换的兼容还没改 要解决的话主动清空一次历史记录，然后远程的也都清理掉，后面就应该都正常了

试了下不起作用，本地和远程的历史记录都删了后再记录后每次退出照样清空记录。每次打开 app 都要手动刷新拉取远程记录
