### ISSUE TITLE
因E站更新导致里站无法加载图片

### ISSUE THREAD

**Issue by RINZE1** [3003h/Eros-FE#372]
https://forums.e-hentai.org/index.php?showtopic=244935
![D5AFCF9B-437F-4FFE-A59B-7BC9271ABF55](https://github.com/user-attachments/assets/1f7fe47e-5348-4cf4-8989-b916b2adccb0)

**Comment by Hanseluwu** [comment]
Same problem

**Comment by fangfaugangchifan** [comment]
是的，就算更新最新版到ehentai设置里面调
Gallery Page Thumbnail Labeling
Show label below gallery thumbnails:
改成None也还是显示不出来

**Comment by vinneotto** [comment]
目前的情况还是没法正常访问画廊 不过倒是能正常下种子

**Comment by Indekkusu545** [comment]
里站结构变化导致无法获取图片数据

**Comment by honjow** [comment]
测试这一版本构建是否解决问题了 https://github.com/3003h/Eros-FE/actions/runs/11539178272

**Comment by vinneotto** [comment]
ios17.6.1可以正常显示里站画廊了
![IMG_3170](https://github.com/user-attachments/assets/b285c5fc-944a-4d62-8251-6cea7b422888)

**Comment by honjow** [comment]
> ios17.6.1可以正常显示里站画廊了 ![IMG_3170](https://private-user-images.githubusercontent.com/186452891/380484754-b285c5fc-944a-4d62-8251-6cea7b422888.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMjMyMjMsIm5iZiI6MTczMDAyMjkyMywicGF0aCI6Ii8xODY0NTI4OTEvMzgwNDg0NzU0LWIyODVjNWZjLTk0NGEtNGQ2Mi04MjUxLTZjZWE3YjQyMjg4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QwOTU1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDFkMGU0MTU2MTRiNzIyYjgxM2UxN2MyYzg4Y2JhNDBjMGIxNTM3NjVjY2EzYzI0OTMzZTY0NTJiNDBkODQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vzKYQxq605Y7jUGOovQA3PZ85znPWj2kUsO0VWXc_mo)

表站正常吗

**Comment by vinneotto** [comment]
不行 切回表站就不显示了
![IMG_3171](https://github.com/user-attachments/assets/d920f43d-5e17-463a-b019-2ed6aea5e9bf)

**Comment by Indekkusu545** [comment]
啊这，表站没更新（）

**Comment by honjow** [comment]
> 啊这，表站没更新（）

加点检查吧🤣

**Comment by honjow** [comment]
再试试 https://github.com/3003h/Eros-FE/actions/runs/11539900155

**Comment by vinneotto** [comment]
试了一下都正常了

**Comment by 520youyou** [comment]
要怎么解决问题呢

**Comment by kenzining** [comment]
> 再试试 https://github.com/3003h/Eros-FE/actions/runs/11539900155

这一版点进所有画廊都显示Parsing data error

**Comment by RINZE1** [comment]
> > 再试试 https://github.com/3003h/Eros-FE/actions/runs/11539900155
> 
> 这一版点进所有画廊都显示Parsing data error

尝试将e站设置中的Gallery Page Thumbnail Labeling 修改为None
![C122FBA1-00DC-422A-B1E0-31B73FEEF185](https://github.com/user-attachments/assets/10c0392a-2fab-489b-8f8e-96878bfc12c9)

**Comment by galerious** [comment]
> > > 再试试 https://github.com/3003h/Eros-FE/actions/runs/11539900155
> > 
> > 
> > 这一版点进所有画廊都显示Parsing data error
> 
> 尝试将e站设置中的Gallery Page Thumbnail Labeling 修改为None ![C122FBA1-00DC-422A-B1E0-31B73FEEF185](https://private-user-images.githubusercontent.com/169538186/380527660-10c0392a-2fab-489b-8f8e-96878bfc12c9.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNzEyMzgsIm5iZiI6MTczMDA3MDkzOCwicGF0aCI6Ii8xNjk1MzgxODYvMzgwNTI3NjYwLTEwYzAzOTJhLTJmYWItNDg5Yi04ZjhlLTk2ODc4YmZjMTJjOS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjdUMjMxNTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWYwNzE5NTg2NTQyMGE4OGExNzNkZTRhNDU4NTQ1ZWQwNDNjOTIxNDFjZWUwYTVhY2Q2YjNkMzdkOWJjNDhlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tIP9NfifBfkmD8YiQfSR1tNmkGQ127FrnvswC9f-mso)

I downloaded the ipa from artifact, checked nope in eh's settings, and still the parsing data error was not fixed.

**Comment by Indekkusu545** [comment]
Please check whether the selected profile is consistent.

![image](https://github.com/user-attachments/assets/5dd6ce83-6d67-45f0-b9ea-000884a22e93)

![image](https://github.com/user-attachments/assets/2896b209-fb53-491f-a83d-19bab789d2d3)

**Comment by jicso** [comment]
这个该怎么下载

**Comment by Indekkusu545** [comment]
> I've applied a new patch, but it still doesn't work. "parsing data error" . Does anyone know a solution to this?![image](https://github.com/user-attachments/assets/586e89fd-b372-48a4-a77a-27a378c5cace)

This is actually another question.

In Settings -> E•H -> EHentai Settings -> Profile, select "FEhViewer". Then the problem would disappear.

**Comment by kmkmkm48-s** [comment]
ios FEhviewer1.5.4，ipad版改了none仍然不能加载出图片，今天早上还是正常的

**Comment by kevinkejc** [comment]
按照我的情况来讲，使用最新版软件，需要以下设置

![image](https://github.com/user-attachments/assets/249037de-1f11-4585-91d5-85d4eff73a3b)
size设置成Auto

![image](https://github.com/user-attachments/assets/dfb8e436-45e5-4820-8d70-cc70ec7ec76a)
Gallery Page Thumbnail Labeling设置成None

这两个设置任意一个如果选项不对，那就弹Parsing data error提示
如还有其他的冲突设置还望补充

**Comment by Tactiiq** [comment]
How do i update the app in order to fix this bug ?

**Comment by kevinkejc** [comment]
> 重新尝试https://github.com/3003h/Eros-FE/actions/runs/11539900155
进入这个链接，拉到网页最下面，即可看到最新版下载链接
我下载的是这个版本：[release-ios-canvas](https://github.com/3003h/Eros-FE/actions/runs/11539900155/artifacts/2109006242)

**Comment by ChrisRamzi** [comment]
Idk what's happening. I tried all of the fix posted before me and it's still not working for some reason. I even tried getting different versions of the app and still... Not working for some reason. 
![Uploading Screenshot_2024-10-29-07-17-36-279_com.honjow.fehviewer.jpg…]()

**Comment by xkforever** [comment]
现在好像看不到下载链接了

**Comment by b3llypunch** [comment]
> 现在好像看不到下载链接了
只要你登录了就能看到吧，如果是你没找对地方的话，上面发的链接拉到最下面就是打包的build release啊
![ADDE7FA7-71C5-4D5F-8D3D-0658CA3661B6](https://github.com/user-attachments/assets/ed189a79-64ed-4cd6-9a7e-bd8600264e75)

**Comment by honjow** [comment]
https://github.com/3003h/Eros-FE/actions/runs/11567459693
测试是否都正常了，无论labeing和缩略图大小设置

**Comment by xkforever** [comment]
正常了，谢谢 @b3llypunch @honjow

**Comment by RINZE1** [comment]
https://github.com/3003h/Eros-FE/releases/tag/v1.7.0
