### ISSUE TITLE
[Feature] Add default favorite

### ISSUE THREAD

**Issue by sanctifyy** [3003h/Eros-FE#373]
### 功能描述 / Feature description

Add a feature where you can select a favorites category to be default, so that when the heart is clicked, it is saved to that favorite by default without asking. When the favorites button is held, then the context menu to select a favorite should pop up. This would streamline the process of adding favorites for a more premium and less clunky feel.

### 备注 / Additional details

This feature does not have to be mandatory and it can selected in settings.

### 自查步骤 / Self-review steps

- [ ] 如果您有足够的时间和能力，并愿意为此功能请求提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/3003h/Eros-FE/issues)，没有找到类似的请求 / I have searched on [Issue Tracker](https://github.com/3003h/FEhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只发起一个功能请求。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request

**Comment by honjow** [comment]
This is one of the early implemented functions. Currently, this setting is
under the EH option. However, the description of the current option might
be a bit problematic. After enabling this option, it will be collected to
the last selected favorite by default. Long press to show the selection.


sanctifyy ***@***.***>于2024年10月26日 周六01:56写道：

**Comment by sanctifyy** [comment]
After some looking I was able to find it, I was a bit confused by the description. Thanks.
